//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perpustakaan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinjamTabel
    {
        public int Id { get; set; }
        public string WaktuPinjam { get; set; }
        public string WaktuKembali { get; set; }
        public int ISBN { get; set; }
    
        public virtual BukuTabel BukuTabel { get; set; }
    }
}
